import { NextResponse } from 'next/server';

export async function GET() {
  return NextResponse.json({
    NEXT_PUBLIC_LEARNHOUSE_API_URL: process.env.NEXT_PUBLIC_LEARNHOUSE_API_URL,
    NEXT_PUBLIC_LEARNHOUSE_BACKEND_URL: process.env.NEXT_PUBLIC_LEARNHOUSE_BACKEND_URL,
    NEXT_PUBLIC_LEARNHOUSE_DOMAIN: process.env.NEXT_PUBLIC_LEARNHOUSE_DOMAIN,
    NEXT_PUBLIC_LEARNHOUSE_TOP_DOMAIN: process.env.NEXT_PUBLIC_LEARNHOUSE_TOP_DOMAIN,
    NEXT_PUBLIC_LEARNHOUSE_MULTI_ORG: process.env.NEXT_PUBLIC_LEARNHOUSE_MULTI_ORG,
    NEXT_PUBLIC_LEARNHOUSE_DEFAULT_ORG: process.env.NEXT_PUBLIC_LEARNHOUSE_DEFAULT_ORG,
    NODE_ENV: process.env.NODE_ENV,
  });
}
